
export ZSH=/usr/share/zsh

source "$ZSH/plugin-managers/zplugin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin

setopt promptsubst
setopt inc_append_history
setopt share_history
setopt extendedglob

if [ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

bindkey -e
bindkey \^U backward-kill-line

source ~/.aliases

export HISTFILE=~/.zsh_history
export HISTSIZE=500
export SAVEHIST=5000

zplugin ice wait lucid atload"_zsh_autosuggest_start"
zplugin light zsh-users/zsh-autosuggestions

zplugin ice wait lucid blockf atpull'zplugin creinstall -q .' as"completion"
zplugin light zsh-users/zsh-completions

zplugin ice wait lucid atinit"zpcompinit; zpcdreplay"
zplugin light zdharma/fast-syntax-highlighting
zplugin ice wait lucid
zplugin load zdharma/history-search-multi-word

zplugin ice depth=1
zplugin light romkatv/powerlevel10k

zplugin ice wait lucid from"gh-r" as"program"
zplugin load junegunn/fzf-bin

zplugin ice wait lucid atclone"dircolors -b LS_COLORS > clrs.zsh" \
    atpull'%atclone' pick"clrs.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zplugin light trapd00r/LS_COLORS

zplugin ice wait lucid from"gh-r" as"program" mv"docker* -> docker-compose" \
    bpick"*linux*" as"completion"
zplugin load docker/compose

# Vim repository on GitHub – a typical source code that needs compilation – Zplugin
# can manage it for you if you like, run `./configure` and other `make`, etc. stuff.
# Ice-mod `pick` selects a binary program to add to $PATH. You could also install the
# package under the path $ZPFX, see: http://zdharma.org/zplugin/wiki/Compiling-programs
#zplugin ice as"program" atclone"rm -f src/auto/config.cache; ./configure" \
 #   atpull"%atclone" make pick"src/vim"
#zplugin light vim/vim

zplugin ice wait lucid as"program" pick"$ZPFX/bin/git-*" make"PREFIX=$ZPFX"
zplugin light tj/git-extras

zplugin ice wait lucid
zplugin snippet OMZ::plugins/kubectl/kubectl.plugin.zsh

zplugin ice wait lucid
zplugin snippet OMZ::plugins/gpg-agent/gpg-agent.plugin.zsh

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
