---

- hosts: all
  roles:
  - {role: base, tags: ['base']}

- hosts: all
  vars_files:
  - vars/user.yml
  - vaulted_vars/password.yml
  roles:
  - {role: user, tags: ['user']}

- hosts: all
  vars_files:
  - vars/user.yml
  roles:
  - {role: dns, tags: ['dns']}
  - {role: gnupg, tags: ['gnupg']}
  - {role: grub, tags: ['grub']}
  - {role: xorg, tags: ['xorg']}
  - {role: xinit, tags: ['xinit']}
  - {role: fonts, tags: ['fonts']}
  - {role: gtk, tags: ['gtk']}
  - {role: terminal, tags: ['terminal']}
  - {role: i3, tags: ['i3']}
  - {role: polybar, tags: ['polybar']}
  - {role: redshift, tags: ['redshift']}
  - {role: sddm, tags: ['sddm']}
  - {role: git, tags: ['git']}

- hosts: all
  vars_files:
  - vars/laptop.yml
  roles:
  - {role: laptop, tags: ['laptop', 'xps']}
