---

- name: make sure xorg is installed
  pacman:
    name:
    - xorg-server

- name: install xorg conf
  copy:
    src: "{{item}}"
    dest: "/etc/X11/xorg.conf.d/{{item}}"
  with_items:
  - 00-keyboard.conf
  - 05-font.conf
  - 50-synaptics.conf
