#!/bin/sh

if [ -d "/sys/bus/pci/drivers/vfio-pci/0000:01:00.0" ]; then
	echo "gpu already bound" >&2
	exit 1
fi

# echo "10de 1f91" > "/sys/bus/pci/drivers/vfio-pci/new_id"
echo "10de 1f91" > "/sys/bus/pci/drivers/vfio-pci/new_id"
