#!/bin/sh

if [ -f "/etc/modprobe.d/disable-cam.conf" ]; then
	echo "cam already disabled"
	exit 1
fi

modprobe -r uvcvideo


# Lock system from loading cam module
mv /etc/modprobe.d/disable-cam.conf.disable /etc/modprobe.d/disable-cam.conf
