#!/bin/sh

msgId="991049"

volume="`pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'`"
mute="$(amixer -c 0 get Master | tail -1 | awk '{print $6}' | sed 's/[^a-z]*//g')"

if [ "$mute" = "off" ]; then
	dunstify -a "Volume" -u low -i audio-volume-muted -r "$msgId" \
		"Volume muted ($volume%)"
	exit 0
fi

icon="audio-volume-high"
if [ "$volume" -le 30 ]; then
	icon="audio-volume-low"
elif [ "$volume" -le 60 ]; then
	icon="audio-volume-medium"
fi

dunstify -a "Volume" -u low -i "$icon" -r "$msgId" "${volume}%"
canberra-gtk-play -i audio-volume-change -d "changeVolume"
