#!/bin/sh

if [ -f "/etc/modprobe.d/disable-nvidia.conf" ]; then
	echo "gpu already disabled"
	exit 1
fi

modprobe -r nvidia_drm
modprobe -r nvidia_uvm
modprobe -r nvidia_modeset
modprobe -r nvidia

# Change NVIDIA card power control
echo -n auto > '/sys/bus/pci/devices/{{ gpu_control.pci_id }}/power/control'
sleep 1
# change PCIe power control
echo -n auto > '/sys/bus/pci/devices/{{ gpu_control.pci_id }}/power/control'
sleep 1

# Lock system from loading nvidia module
mv /etc/modprobe.d/disable-nvidia.conf.disable /etc/modprobe.d/disable-nvidia.conf

if [ $# -ge 1 ] && [ "$1" = "--bind" ]; then
	sleep 1
	/usr/local/bin/bindgpu
fi

exit 0
