---

- name: install needed packages for yubikey & gnupg
  pacman:
    name:
    - gnupg
    - pcsclite
    - openssh-askpass
    - ccid
    - hopenpgp-tools
    - yubikey-personalization

- name: create gnupg directory
  file:
    path: ~/.gnupg
    mode: 0700
    state: directory
  become: yes
  become_user: "{{user.name}}"

- name: install gnupg and gpg-agent conf
  copy:
    src: "{{item}}"
    dest: "~/.gnupg/{{item}}"
  become: yes
  become_user: "{{user.name}}"
  with_items:
  - gpg.conf
  - gpg-agent.conf

- name: import gpg key
  shell: gpg --keyserver keyserver.ubuntu.com --recv-keys 8154CA537DDB2F08
  register: import_key
  changed_when: "'not changed' not in import_key.stderr"
