---

- name: install needed packages for yubikey & gnupg
  pacman:
    name:
      - gnupg
      - pcsclite
      - openssh-askpass
      - ccid
      - hopenpgp-tools
      - yubikey-personalization

- name: create gnupg directory
  file:
    path: ~/.gnupg
    mode: 0700
    state: directory
  become: yes
  become_user: "{{ user.name }}"

- name: install gnupg and gpg-agent conf
  copy:
    src: "{{ item }}"
    dest: "~/.gnupg/{{ item }}"
  become: yes
  become_user: "{{ user.name }}"
  with_items:
  - gpg.conf
  - gpg-agent.conf

- name: import gpg key
  shell: gpg --keyserver keyserver.ubuntu.com --recv-keys 0x9613cd9cd4e9b8084dd758c98154ca537ddb2f08
  register: import_key
  changed_when: "'not changed' not in import_key.stderr"
  become: yes
  become_user: "{{ user.name }}"

- name: retrieve ssh public key
  shell: ssh add -L | grep cardno > ~/.ssh/id_rsa_yubikey.pub
  args:
    creates: ~/.ssh/id_rsa_yubikey.pub
  become: yes
  become_user: "{{ user.name }}"
