---

- name: service cronie
  service:
    name: cronie.service
    state: started
    enabled: yes

- name: service dnscrypt-proxy
  service:
    name: dnscrypt-proxy.service
    state: restarted
    enabled: yes

- name: generate resolv.conf
  shell: resolvconf -u
