---

- name: install systemd services
  copy:
    src: disable-nvidia-on-shutdown.service
    dest: /etc/systemd/system/disable-nvidia-on-shutdown.service
  notify: enable nvidia disable service

- name: install binaries
  template:
    src: gpucli
    dest: /usr/local/bin/gpucli
    mode: 0755

- name: install modprobe disable nvidia
  copy:
    src: disable-nvidia.conf
    dest: /etc/modprobe.d/disable-nvidia.conf

- name: install xorg conf
  copy:
    src: 20-intel.conf
    dest: /etc/X11/xorg.conf.d/20-intel.conf
