---

- name: install modprobe conf
  copy:
    src: "{{item}}"
    dest: "/etc/modprobe.d/{{item}}"
  with_items:
  - blacklist.conf
  - disable-cam.conf
  - disable-ipmi.conf
  - i915.conf
  - powersave.conf
  - kvm.conf
  - scsi_mod.conf
  
- name: install binaries
  copy:
    src: "{{item}}"
    dest: "/usr/local/bin/{{item}}"
    mode: 0755
  with_items:
  - disablecam
  - enablecam

- name: install disable cam services
  copy:
    src: disable-cam-on-shutdown.service
    dest: /etc/systemd/system/disable-cam-on-shutdown.service
  with_items:
  - disable-cam-on-shutdown.service
  notify: enable cam disable service

- name: make sure synaptic is not installed
  pacman:
    name: xf86-input-synaptics
    state: absent

- name: uninstall synaptics conf
  file:
    path: /etc/X11/xorg.conf.d/50-synaptics.conf
    state: absent

- name: install libinput
  pacman:
    name:
    - xf86-input-libinput
    - xorg-xinput

- name: install xorg conf
  copy:
    src: "{{item}}"
    dest: "/etc/X11/xorg.conf.d/{{item}}"
  with_items:
  - 01-noautogpu.conf
  - 42-libinput.conf

- name: install tmpfiles.d
  copy:
    src: pcie_powersave.conf
    dest: /etc/tmpfiles.d/pcie_powersave.conf

- name: include gpu control task
  include: gpu_control.yml
  when: "gpu_control.enabled"

- name: include dell tweaks
  include: dell.yml
  when: "dell_tweaks"

- name: include xps 15 tweaks
  include: xps_15.yml
  when: "xps_15_tweaks"
