---

- name: install i3 packages
  pacman:
    state: present
    name:
    - i3
    - nitrogen
    - rofi
    - compton
    - python-pip
    - binutils
    - gcc
    - make
    - pkg-config
    - dunst
    - fakeroot

- name: create i3 conf directory
  file:
    path: ~/.config/i3
    mode: 0700
    state: directory
  become: yes
  become_user: "{{user.name}}"

- name: install i3 conf
  copy:
    src: config
    dest: ~/.config/i3/config
  become: yes
  become_user: "{{user.name}}"

- name: create nitrogen conf directory
  file:
    path: ~/.config/nitrogen
    mode: 0700
    state: directory
  become: yes
  become_user: "{{user.name}}"

- name: copy nitrogen files
  copy:
    src: "{{item}}"
    dest: "~/.config/nitrogen/{{item}}"
  with_items:
  - bg-saved.cfg
  - wallpaper.jpg
  become: yes
  become_user: "{{user.name}}"

- name: create dunst conf directory
  file:
    path: ~/.config/dunst
    mode: 0700
    state: directory
  become: yes
  become_user: "{{user.name}}"

- name: copy dunstrc
  copy:
    src: dunstrc
    dest: ~/.config/dunst/dunstrc
  become: yes
  become_user: "{{user.name}}"
