---

- name: install urxvt truecolor
  aur:
    name: rxvt-unicode-truecolor
    use: pikaur

- name: install zsh dotfiles
  copy:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
  loop:
    - zshrc
    - zprofile
    - aliases
  become: yes
  become_user: "{{ user.name }}"

- name: create plugin-managers dir
  file:
    path: /usr/share/zsh/plugin-managers
    state: directory

- name: install zplugin
  git:
    dest: /usr/share/zsh/plugin-managers/zplugin
    repo: https://github.com/zdharma/zplugin.git
  register: zplugin_install

- name: install cronie
  pacman:
    name: cronie

- name: install zplugin update script
  copy:
    src: "{{ item }}"
    dest: "/usr/share/zsh/plugin-managers/{{ item }}"
    mode: "755"
  loop:
    - zplugin_update.sh
    - zplugin_update-plugin.sh

- name: update zplugin
  shell: /usr/share/zsh/plugin-managers/zplugin_update.sh
  when: zplugin_install.changed

- name: install zplugin update cron
  cron:
    name: zplugin_update
    minute: "*/30"
    user: "root"
    job: "/usr/share/zsh/plugin-managers/zplugin_update.sh"
    cron_file: ansible_zplugin-update

- name: install zplugin plugin update cron
  cron:
    name: zplugin_plugin_update
    minute: "*/30"
    user: "{{ user.name }}"
    job: "/usr/share/zsh/plugin-managers/zplugin_update-plugin.sh"
    cron_file: ansible_zplugin-update_plugin

- name: install Xresources
  copy:
    src: Xresources
    dest: ~/.Xresources
  become: yes
  become_user: "{{ user.name }}"

- name: install vim
  pacman:
    name: vim

- name: install ctags
  pacman:
    name: ctags

- name: install vimrc
  copy:
    src: vimrc
    dest: ~/.vimrc
  become: yes
  become_user: "{{ user.name }}"
  register: vimrc

- name: install vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
  register: vundle
  become: yes
  become_user: "{{ user.name }}"

- name: install vundle plugins
  shell: vim +PluginInstall +qall
  when: vimrc.changed or vundle.changed

- name: create urxvt directory
  file:
    path: ~/.urxv/ext
    state: directory
    recurse: yes
  become: yes
  become_user: "{{ user.name }}"

- name: download urxvt font-size
  get_url:
    url: "https://raw.githubusercontent.com/majutsushi/urxvt-font-size/master/font-size"
    dest: ~/.urxv/ext/font-size
  become: yes
  become_user: "{{ user.name }}"
